-- instagram_posts 全データ削除 + 既存記事データ再投入
-- case: 139件
-- column: 84件
-- 合計: 221件（重複排除・URLありのみ）

DELETE FROM instagram_posts;

INSERT INTO instagram_posts (url, shortcode, source, caption, posted_at, classification, status)
VALUES
  ('https://www.instagram.com/p/CqSXkeQuSlN/', 'CqSXkeQuSlN', 'doctor', 'ヒアルロン酸注入で整える横顔｜あご+唇で小顔効果とEライン改善', '2026-04-01', 'case', 'published'),
  ('https://www.instagram.com/p/CqhR9ePSh6I/', 'CqhR9ePSh6I', 'doctor', 'サーマジェン（RF）でフェイスラインを引き締めたるみを改善した症例', '2026-04-01', 'case', 'published'),
  ('https://www.instagram.com/p/Cr0HZxDu0va/', 'Cr0HZxDu0va', 'doctor', 'M字リップと口角挙上の組み合わせで口元の印象を整える（術後1週間）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/Cr5B3JVOCKK/', 'Cr5B3JVOCKK', 'doctor', '糸リフト×サーマジェン×ヒアルロン酸のコンビネーション治療でフェイスラインを整える', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CsA_rsnuCBD/', 'CsA_rsnuCBD', 'doctor', '眼瞼下垂手術（切開法）で目の開きと眉の左右差を改善した症例（術後1週間）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CsYNRDBOzq-/', 'CsYNRDBOzq-', 'doctor', '糸リフトとあごボトックスで四角くなった輪郭を整えた症例（術後1週間）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/Csk_HlYObOK/', 'Csk_HlYObOK', 'doctor', 'サーマジェン（RF）×あごヒアルロン酸でフェイスラインをすっきり整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CsqWoa9ycIs/', 'CsqWoa9ycIs', 'doctor', '男性の二重埋没で左右差を改善し精悍な目元に（術後1ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/Csu_yMFyinY/', 'Csu_yMFyinY', 'doctor', 'M字リップ×口角挙上でいつ撮られても口角が上がった口元に（術後1ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/Cs8aa35yKM5/', 'Cs8aa35yKM5', 'doctor', '眉下切開でまぶたのたるみを改善し少し昔の自分に戻った症例（術後1ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CtGgnDsuXiY/', 'CtGgnDsuXiY', 'doctor', '口角挙上でナチュラルに口角を上げ「不機嫌そう」な印象を改善した症例（術後1ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CtJFI6bu7pT/', 'CtJFI6bu7pT', 'doctor', '眼瞼下垂手術で黒目の見える範囲が広がり目に入る光が増えた症例（術後1ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CtbUoKKyBXY/', 'CtbUoKKyBXY', 'doctor', '額・こめかみへのヒアルロン酸注射で顔に丸みと女性らしい柔らかい印象を出した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CtnrtcjSsqV/', 'CtnrtcjSsqV', 'doctor', '首のアトピー性皮膚炎にポテンツァ×エクソソーム×メソナJで肌の炎症と赤みを改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CttIGAXucOh/', 'CttIGAXucOh', 'doctor', '鼻孔縁下降＋鼻尖形成＋耳介軟骨移植で鼻の穴の目立ちを改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CuOucfoSjgo/', 'CuOucfoSjgo', 'doctor', '骨格に合わせた自然な末広二重で周りにバレない変化を実現した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CuY4hV4OzvW/', 'CuY4hV4OzvW', 'doctor', '他院修正の口角挙上でしっかりと口角を上げ印象を改善した症例（術後1ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CvBzo5FSyIa/', 'CvBzo5FSyIa', 'doctor', '口角形成で真顔でも笑顔でも印象が上がった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CvO_mIvOAYT/', 'CvO_mIvOAYT', 'doctor', '眉下切開術後1週間（抜糸前）のダウンタイムの経過', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CvhFHL8uIeJ/', 'CvhFHL8uIeJ', 'doctor', '口角挙上で真顔でも印象の良い口元に整えた症例（術後1ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CvjrXJHOzUZ/', 'CvjrXJHOzUZ', 'doctor', '口角形成で笑顔がきれいになりぎこちなさが改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/Cv1nVfduuAK/', 'Cv1nVfduuAK', 'doctor', '眉下切開＋二重埋没でたるみで隠れていた二重ラインをすっきり出した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CwPaq5SOQUF/', 'CwPaq5SOQUF', 'doctor', '眉下切開で埋もれた二重とまつ毛を復活させ昔の目元に戻した症例（術後3ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CwcO7E7OAld/', 'CwcO7E7OAld', 'doctor', '口角挙上で笑いやすさと口角の上がりを同時に改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/Cw4BSJwSYb5/', 'Cw4BSJwSYb5', 'doctor', 'ボトックス×ヒアルロン酸（頬・唇）のトータル注入で上品な印象に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/Cxh74wUyz-G/', 'Cxh74wUyz-G', 'doctor', '口角挙上でふとした瞬間の口角を上げ第一印象を改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CxsLR74ybv0/', 'CxsLR74ybv0', 'doctor', '鼻根部＋あごへのヒアルロン酸注射で鼻筋とフェイスラインのバランスを整えた症例（1ヶ月後）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CxxUwUXyzs7/', 'CxxUwUXyzs7', 'doctor', '鼻＆あごヒアルロン酸で光の集まり方が変わり華やかな印象になった症例（1ヶ月後）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/Cx7rf10SfKD/', 'Cx7rf10SfKD', 'doctor', 'ショートスレッドで口横のたるみ・ゆるみを引き締めた症例（施術後1ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CyDS3qqOCQy/', 'CyDS3qqOCQy', 'doctor', '骨格に合わせた自然な末広二重埋没で周りにバレない変化を実現した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/CyS1zmIy4nY/', 'CyS1zmIy4nY', 'doctor', 'ボトックス×ヒアルロン酸×サーマジェンのコンビネーション治療で下顔面を整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/Cz8TpyjyyaQ/', 'Cz8TpyjyyaQ', 'doctor', 'ジャルプロ＋ショートスレッド＋シルキー注射＋口角挙上の複合治療で口横のたるみを整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C2CK9pIySAY/', 'C2CK9pIySAY', 'doctor', '眼瞼下垂手術で黒目全体が見えるようになり目の開きと印象を改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C2MpP5-SLZ3/', 'C2MpP5-SLZ3', 'doctor', '眉下切開でまぶたのもたつきをすっきり改善した症例（術後6ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C2Rr00jygsb/', 'C2Rr00jygsb', 'doctor', '口角挙上でふとした瞬間も口角が下がらない印象の良い口元になった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C2mbZvWSkA1/', 'C2mbZvWSkA1', 'doctor', '糸リフト＋サーマジェン＋ヒアルロン酸＋ボトックスのコンビネーションでバランス良く小顔に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C3CkcVDyxM5/', 'C3CkcVDyxM5', 'doctor', '脱脂（くまとり）＋グラマラス（たれ目形成）で中顔面が短く見える丸い目元に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C3M_2rkSAE-/', 'C3M_2rkSAE-', 'doctor', '口角挙上で「口角が下がっていない」自然な口元の印象を整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C3cRDIbubnh/', 'C3cRDIbubnh', 'doctor', '表ハムラでたるみ・膨らみ・へこみをまとめて改善した目の下クマの症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C3jVpl0S2pI/', 'C3jVpl0S2pI', 'doctor', 'シルキー注射＋ジャルプロスーパーハイドロの肌育で目周りの小じわと乾燥を改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C3zpxtbSPbD/', 'C3zpxtbSPbD', 'doctor', '口角挙上で真顔でも斜めから見ても口角が下がっていない自然な口元に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C32WA7SSfJD/', 'C32WA7SSfJD', 'doctor', '口角挙上で笑いやすく笑顔が綺麗になった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C4NY3jTylqw/', 'C4NY3jTylqw', 'doctor', '糸リフト＋脂肪吸引の組み合わせでしっかり小顔に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C4sVo3Qy5mv/', 'C4sVo3Qy5mv', 'doctor', '二重全切開の傷跡が目立ちにくい理由と実際の経過を示した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C4xXVi0ylTp/', 'C4xXVi0ylTp', 'doctor', '糸リフト＋ショートスレッド＋ヒアルロン酸でフェイスラインをすっきり整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C5Dc8r5ys75/', 'C5Dc8r5ys75', 'doctor', '二重幅と自然な二重ラインを意識した二重埋没でまつ毛が上向きにきれいに出た症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C5a25PByOKS/', 'C5a25PByOKS', 'doctor', 'M字リップ＋口角挙上の複合手術でかわいくメリハリのある口元に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C5f3ORTyKau/', 'C5f3ORTyKau', 'doctor', '他院目頭切開後の蒙古ひだ形成修正で目頭が入り込みすぎた印象を自然に改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C5siZO5OWQ0/', 'C5siZO5OWQ0', 'doctor', 'スキンブースターの肌育で毛穴の赤みと乾燥・炎症を改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C5-xh9NSHPM/', 'C5-xh9NSHPM', 'doctor', 'リガメント処理を含む裏ハムラで脱脂後に改善しなかった目の下のへこみを解消した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C6OBaK0Sgyz/', 'C6OBaK0Sgyz', 'doctor', '二重全切開修正のダウンタイム経過（術直後〜1ヶ月）を解説した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C6nHKeUy4Yl/', 'C6nHKeUy4Yl', 'doctor', 'サーマジェン（RF）で顔の引き締めと小顔効果を実現した症例（施術直後）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C6vt48qS6S_/', 'C6vt48qS6S_', 'doctor', 'あごのヒアルロン酸で輪郭のバランスを自然に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C71XGUWSmsB/', 'C71XGUWSmsB', 'doctor', '40代の口角挙上でほほえんだ口元の上品な印象を整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C8ZMa9VSgbe/', 'C8ZMa9VSgbe', 'doctor', '口角挙上＋糸リフトの直後ダウンタイム経過を示した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C8wRRL9Sr1v/', 'C8wRRL9Sr1v', 'doctor', '目頭上切開＋二重埋没で目と目の距離を保ちながら目元を大きく見せた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C9KKhgjSVxY/', 'C9KKhgjSVxY', 'doctor', '口角挙上＋糸リフト術後1週間のダウンタイム経過を示した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C9j6WG3S2ZE/', 'C9j6WG3S2ZE', 'doctor', '眉下切開で少し昔の自分に戻るアンチエイジング効果を実感した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C91vmJTSNMH/', 'C91vmJTSNMH', 'doctor', '他院人中短縮後の口角挙上＋外側人中で唇全体のバランスを整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C-SAoKESu8p/', 'C-SAoKESu8p', 'doctor', '口角挙上で笑いやすさと笑顔の印象を同時に改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C-XQw-myWa9/', 'C-XQw-myWa9', 'doctor', 'KOライトで術後の腫れと内出血を大幅に軽減したダウンタイム対策症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C-sDXVQy4UZ/', 'C-sDXVQy4UZ', 'doctor', '口角挙上で真顔でも口角が上がり印象が良くなった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C-xFGQ5y24Y/', 'C-xFGQ5y24Y', 'doctor', '眉下切開＋目頭上切開でまぶたを全体的にすっきりさせた症例（術後1週間）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C-ziTlOSs-4/', 'C-ziTlOSs-4', 'doctor', 'KOライト2日連続照射で他院フェイスリフト後の内出血と腫れを大幅に改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C-7RaqcygwZ/', 'C-7RaqcygwZ', 'doctor', '他院眉下切開後の赤みと凹みが残る傷跡をポテンツァで改善した修正症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C--IuMQSbwy/', 'C--IuMQSbwy', 'doctor', '口角挙上の傷跡が目立ちにくい理由と口角形成の変化を示した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C_FnZaFS8eo/', 'C_FnZaFS8eo', 'doctor', 'KOライトで術後の腫れと黄色い内出血を素早く改善したダウンタイム対策症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C_K1Ngcyazd/', 'C_K1Ngcyazd', 'doctor', '口角挙上でふとした瞬間・斜めから見ても口角が上がっている印象の良い口元に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C_kohF0yjkP/', 'C_kohF0yjkP', 'doctor', 'あごのヒアルロン酸注射で輪郭のバランスを整え小顔効果が期待できた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/C_plUfqy8P3/', 'C_plUfqy8P3', 'doctor', '眉下切開のダウンタイム中にメガネで傷跡を目立たなくする方法を紹介した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DAdLXimSZ-n/', 'DAdLXimSZ-n', 'doctor', '20代の眉下切開でまぶたの被さりを改善し本来の二重ラインを取り戻した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DAiP_bVySAE/', 'DAiP_bVySAE', 'doctor', '男性の口角挙上＋サーマジェンでフェイスラインのもたつきも整えた症例（術後1ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DA0jDt6T4ZD/', 'DA0jDt6T4ZD', 'doctor', '口角挙上＋M字リップの複合手術でより女性らしい立体的な唇に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DA3F0wNSqLF/', 'DA3F0wNSqLF', 'doctor', 'ルビーフラクショナルレーザーで細かいシミとそばかすを改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DBD7nCgzQGp/', 'DBD7nCgzQGp', 'doctor', '口角挙上で笑いにくさを改善しより魅力的な笑顔になった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DBqWh4Mz80e/', 'DBqWh4Mz80e', 'doctor', 'ホルモンバランスを整える内服とIPLフォトフェイシャルでニキビと赤みを改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DCyno_Py5ax/', 'DCyno_Py5ax', 'doctor', '表ハムラ＋ヒアルロン酸注射＋シルキー注射で男性の自然な若返りを実現した症例（半年以上後）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DC_j8i3yk4Y/', 'DC_j8i3yk4Y', 'doctor', '糸リフトの適材適所な使い分けでフェイスラインを自然に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DDGjSGjSXLS/', 'DDGjSGjSXLS', 'doctor', '二重全切開で二重ラインの左右差と余分なラインを改善した症例（術後2ヶ月）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DD9T2RhygF-/', 'DD9T2RhygF-', 'doctor', '口角挙上で笑顔としゃべりやすさも改善した術後3ヶ月の長期経過症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DET3lYNyLnp/', 'DET3lYNyLnp', 'doctor', 'KOライトで年末手術後の腫れと内出血を改善し仕事始めに備えたダウンタイム対策症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DEmU08Kypih/', 'DEmU08Kypih', 'doctor', '手の甲へのヒアルロン酸注射でふっくら若々しい手元に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DEri7b3S_vN/', 'DEri7b3S_vN', 'doctor', '口角挙上＋外側人中で口角と唇両方の下りを改善しバランスを整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DFfRn_myev0/', 'DFfRn_myev0', 'doctor', 'シルキー注射（スキンブースター）で光老化による真皮ダメージを根本から改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DFr9iUeyogC/', 'DFr9iUeyogC', 'doctor', '眼瞼下垂の切開法・埋没法の違いと手術の変化を解説した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DFzfpR7S8C_/', 'DFzfpR7S8C_', 'doctor', '口角挙上でナチュラルに上品な変化を実現した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DGDFrbRzjGJ/', 'DGDFrbRzjGJ', 'doctor', '口角挙上で笑顔が変わり笑いやすさとお顔の余白改善を実現した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DGknOVASOMe/', 'DGknOVASOMe', 'doctor', '眼瞼下垂手術で本来の自分の目元を取り戻した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DHFgbq7y0A4/', 'DHFgbq7y0A4', 'doctor', 'ザーフ（XERF）直後のフェイスラインのピタッとした引き締め効果を実感した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DHQTMF5Shfx/', 'DHQTMF5Shfx', 'doctor', 'ウルトラセルZi（HIFU）＋ザーフ（RF）の組み合わせでたるみを全層引き締めた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DHiN8zzS-eV/', 'DHiN8zzS-eV', 'doctor', '脱脂（経結膜脱脂）で目の下の膨らみを改善し明るく元気な印象になった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DIBMHAfz1w6/', 'DIBMHAfz1w6', 'doctor', '睫毛上切開＋目頭上切開でハム目を修正し綺麗な目元に整えた症例（術後1週間）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DIOIqr8TYri/', 'DIOIqr8TYri', 'doctor', '口角挙上で印象アップと中顔面短縮による小顔効果を実現した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DITSYYTzH6I/', 'DITSYYTzH6I', 'doctor', '口角挙上でつっぱりが解除され笑顔がかわいくなった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DIa7IH_T5zb/', 'DIa7IH_T5zb', 'doctor', 'おでこのボトックス後に生じたスポックブローをオビソートで調整した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DIgQ4P5TbDE/', 'DIgQ4P5TbDE', 'doctor', '眉下切開でまぶたのたるみを自然に改善し少し昔の自分に戻った症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DIn-V7MTREq/', 'DIn-V7MTREq', 'doctor', '口角挙上でふとした瞬間も口角が下がらずかわいい印象をキープした症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DJBsUEkTcqx/', 'DJBsUEkTcqx', 'doctor', 'KOライトでゴールデンウィーク手術後の腫れと内出血を軽減したダウンタイム対策症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DJL0rF6zx6h/', 'DJL0rF6zx6h', 'doctor', 'ポテンツァで鼻の毛穴を皮脂コントロールから引き締めまでオーダーメイドに改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DJOmeKPTmi_/', 'DJOmeKPTmi_', 'doctor', '口角挙上＋M字リップで唇の黄金比に近づけ上品な印象に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DJWU0X5zD4B/', 'DJWU0X5zD4B', 'doctor', '眼瞼下垂手術で黒目全体が見えるようになりまつ毛も上向きになった症例（術後1週間）', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DJlwUndzxT_/', 'DJlwUndzxT_', 'doctor', '眉下切開＋目頭上切開でまぶたのたるみを全体的に改善し斜め方向も綺麗になった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DJtVIfLTLl2/', 'DJtVIfLTLl2', 'doctor', '口角挙上＋外側人中＋人中短縮の複合治療で唇と口元全体のバランスを整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DJ_bA4HT1lC/', 'DJ_bA4HT1lC', 'doctor', '口角挙上＋ヒアルロン酸で術後6ヶ月笑顔が格段に良くなった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DKRdvHtzkpu/', 'DKRdvHtzkpu', 'doctor', '目頭上切開で目頭側のたるみを改善しどこから見てもすっきりした丸い目元に整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DK_4O-kzzxz/', 'DK_4O-kzzxz', 'doctor', '口角挙上で笑い方の悩みを解消し笑顔に自信が持てるようになった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DLexsJ9z7Yc/', 'DLexsJ9z7Yc', 'doctor', '眼瞼下垂手術で隠れた黒目を見せ目の開きと印象を大きく改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DLme2cyzWUO/', 'DLme2cyzWUO', 'doctor', '口角挙上でバレずに自然な印象アップと笑顔の改善を実現した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DL9pqEGTJ3_/', 'DL9pqEGTJ3_', 'doctor', 'サーマハンドで気になる頬や口横をピンポイントに引き締めたオーダーメイド施術症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DMC82ENTpmv/', 'DMC82ENTpmv', 'doctor', '口角挙上で口角のつっぱりを解除し笑顔が変わった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DMSRzWISLuk/', 'DMSRzWISLuk', 'doctor', '睫毛上切開でまつ毛と二重ラインの間のもたつきを改善しすっきりした目元にした症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DMXYv8AzV-S/', 'DMXYv8AzV-S', 'doctor', '片側口角挙上で口角の左右差を整えた術後3ヶ月の症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DM2LTKAuofx/', 'DM2LTKAuofx', 'doctor', '二重埋没で乱れた二重ラインと左右差を改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DNKLC58yNAJ/', 'DNKLC58yNAJ', 'doctor', 'マルチフィル＋フラットリフト＋糸リフトでほうれい線の段差を平らにした症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DNnNVRZyMAk/', 'DNnNVRZyMAk', 'doctor', '厚生労働省承認機ソフウェーブで小じわとたるみを改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DNuNIXk5if9/', 'DNuNIXk5if9', 'doctor', 'ソフウェーブであご下フェイスラインの皮膚のたるみをピタッと引き締めた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DN2srwkZnkm/', 'DN2srwkZnkm', 'doctor', 'ソフウェーブで目周りの小じわをアイロンのようにピンと伸ばした症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DN7riVBk26A/', 'DN7riVBk26A', 'doctor', '口角挙上＋ショートスレッドで印象アップと輪郭の引き締めを同時に実現した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DONvhc5E2EF/', 'DONvhc5E2EF', 'doctor', '口角挙上術後1年の長期経過で笑いやすさ・しゃべりやすさも維持している症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DOf5ICIE-0Y/', 'DOf5ICIE-0Y', 'doctor', '外側人中手術で唇の外側の下りを改善しお顔の余白を減らした症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DOnh25Rk0S-/', 'DOnh25Rk0S-', 'doctor', 'ソフウェーブでほうれい線・小じわ・毛穴をまとめて改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DOvWEB8k_ua/', 'DOvWEB8k_ua', 'doctor', 'ヒアルロン酸注射でバランス良く整え自然にリフトアップした症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DOx0QhXE4bm/', 'DOx0QhXE4bm', 'doctor', '外側人中の傷跡が目立ちにくい位置と形成外科的なこだわりを示した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DPFwMfVkw3h/', 'DPFwMfVkw3h', 'doctor', '口角挙上＋ヒアルロン酸で笑顔が良くなり唇のバランスも整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DPQ4tpsk_4g/', 'DPQ4tpsk_4g', 'doctor', '外側人中短縮で唇の外側を持ち上げお顔の余白を改善した術後1ヶ月の症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DPTUmWnk4Ic/', 'DPTUmWnk4Ic', 'doctor', '口角挙上で不機嫌そうに思われる悩みを解決した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DPqMvPjk-9Z/', 'DPqMvPjk-9Z', 'doctor', '口角挙上＋ジャルプロスーパーハイドロで口元の若返りを実現した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DQlzmBck-Eb/', 'DQlzmBck-Eb', 'doctor', '口角挙上＋糸リフトで笑い方の邪魔を取り除き上品な笑顔になった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DQ6MQovkoxb/', 'DQ6MQovkoxb', 'doctor', 'ブレッシングで頑固な毛穴をニードルRFと薬剤の相乗効果で改善した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DREj0qqE9p3/', 'DREj0qqE9p3', 'doctor', '人中短縮＋外側人中＋口唇拡大で唇を全方位から拡大した術後1週間の症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DRjndGbk9Qd/', 'DRjndGbk9Qd', 'doctor', 'シミ治療のオーダーメイド戦略でお肌の状態に合わせた最適な治療を提案した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DRy68gTkwMf/', 'DRy68gTkwMf', 'doctor', '外側人中手術で唇のバランスを立体的に改善し口元の印象を整えた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DSCTeLVk4Uq/', 'DSCTeLVk4Uq', 'doctor', '人中短縮＋口角挙上で顔の余白を大幅に減らし小顔効果を実現した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DTKfgICE7YB/', 'DTKfgICE7YB', 'doctor', '眼瞼下垂手術術後1週間（抜糸前）のダウンタイム経過を記録した症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DTudTcqEm1J/', 'DTudTcqEm1J', 'doctor', 'ブレッシングで毛穴レス肌を目指した広範囲ニードルRFと薬剤の複合施術症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DVvMzySk4tf/', 'DVvMzySk4tf', 'doctor', '口角挙上で笑顔のぎこちなさを改善し自信を持って笑えるようになった症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/p/DVvNtIaEqUM/', 'DVvNtIaEqUM', 'doctor', 'ソフウェーブで30代のフェイスラインのたるみをピタッと引き締めた症例', '2026-04-02', 'case', 'published'),
  ('https://www.instagram.com/hirose_masashi_1/p/DPFwMfVkw3h/', 'DPFwMfVkw3h', 'doctor', '口角挙上で笑顔の印象が変わる｜つっぱり解消で自然な笑顔に', '2025-09-27', 'case', 'published'),
  ('https://www.instagram.com/p/Cs8e_0fSk6m/', 'Cs8e_0fSk6m', 'clinic', 'たるみの原因は全層にある｜浅層・深層それぞれのアプローチと治療メニュー', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/CtEEmZnuZqr/', 'CtEEmZnuZqr', 'clinic', 'メソナJとは｜塗布の300倍浸透するメソポレーション法の仕組みと料金', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/CtnSN49yaxJ/', 'CtnSN49yaxJ', 'clinic', 'セレックVとは｜IPL光治療機器の9波長フィルターでシミ・赤み・ニキビを一台で改善', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/Ct1GILYyrrP/', 'Ct1GILYyrrP', 'clinic', 'サーマジェンとは｜RF照射でたるみを改善するMaison PUREJUのこだわり5ステップ', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/CuHBhCfys3l/', 'CuHBhCfys3l', 'clinic', 'ウルトラセルZiとは｜0.5mm単位でカスタマイズできるHIFUのオーダーメイドたるみ治療', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/Cu50kN1yCLj/', 'Cu50kN1yCLj', 'clinic', 'ポテンツァとは｜多彩なチップと薬剤で毛穴・ニキビ跡・たるみをオーダーメイドで改善', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/Cu9IcIrS2T-/', 'Cu9IcIrS2T-', 'clinic', 'ジェネシスとは｜ロングパルスYAGレーザーで毛穴・赤ら顔・くすみをオールシーズン改善', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/CvhEbSAu0Yp/', 'CvhEbSAu0Yp', 'clinic', 'カスタマイズトーニングとは｜肝斑・くすみ・毛穴をダブルパルスで改善するレーザー治療', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/CvrfHvCyquz/', 'CvrfHvCyquz', 'clinic', 'ルビーフラクショナルとは｜光治療で消えないシミ・ADMをダウンタイム短めで改善', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/Cv4ULR8ulLi/', 'Cv4ULR8ulLi', 'clinic', '1064フラクショナルとは｜衝撃波で毛穴・ニキビ跡・小じわをコラーゲン再生で改善', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/CwSA7EzSEQ9/', 'CwSA7EzSEQ9', 'clinic', '夏の紫外線ダメージを回復させる美容医療3選｜ペパーミントピール・メソナJ・高濃度VC点滴', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/CwUo3g3yEAU/', 'CwUo3g3yEAU', 'clinic', '外科手術を受けた方へ｜皮膚科治療20%オフで「外科×皮膚科」の両面ケアを', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/Cwzjs7-yLhv/', 'Cwzjs7-yLhv', 'clinic', 'うるおいSilky注射とは｜数十種類の美容有効成分を直接注入する当院オリジナルスキンブースター', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/Cxm8HgGyImd/', 'Cxm8HgGyImd', 'clinic', 'シミ治療の選び方｜ルビーフラクショナルとIPL（セレックV）の違いを徹底比較', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/Czs8wo0ScGQ/', 'Czs8wo0ScGQ', 'clinic', 'シミ治療の3ステップ｜プレ・照射・アフターケアまで一貫して行うMaison PUREJUのアプローチ', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/Cz8JRaMyj-O/', 'Cz8JRaMyj-O', 'clinic', 'ダウンタイムを最短に！施術後におすすめのスキンケア4選｜EGF・幹細胞配合アイテム', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C0Ec0jKy18H/', 'C0Ec0jKy18H', 'clinic', 'ゆらぎ肌の原因と治療｜赤みの種類（乾燥・炎症・真皮の衰え・血管拡張）で選ぶアプローチ', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C0ldO41yy7x/', 'C0ldO41yy7x', 'clinic', 'マヌカピールとは｜3種のMIX酸×マヌカハニーで毛穴・ニキビ・くすみをダウンタイム少なく改善', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C03jfJvSWnx/', 'C03jfJvSWnx', 'clinic', 'ジャルプロスーパーハイドロとは｜リガメントを強化してたるみ・ハリを根本から改善する注入治療', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C1T7Y_IS4Em/', 'C1T7Y_IS4Em', 'clinic', 'ダウンタイムを上手に隠す4つのアイテム｜帽子・サングラス・マスク・ストールの選び方', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C3KV_MRygEV/', 'C3KV_MRygEV', 'clinic', '糸リフトとは｜種類・材質・本数の目安からMaison PUREJUの3プランまで徹底解説', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C3Unqb7ygt9/', 'C3Unqb7ygt9', 'clinic', '糸リフト7種類を徹底解説②｜スパイラル・ロイヤル・テスリフト・ミントリフトなど各糸の特徴と使い分け', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C3mo3JWufpj/', 'C3mo3JWufpj', 'clinic', 'HIFUはどこでも同じ？｜Maison PUREJUのウルトラセルZiオーダーメイド照射3つのこだわり', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C3o1hSZyi5a/', 'C3o1hSZyi5a', 'clinic', 'スタッフが実際に使う洗顔アイテム3選｜レカルカ・プラスリストア・エムディアのリアルレビュー', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C4sQcZ_yY6d/', 'C4sQcZ_yY6d', 'clinic', 'サーマジェン（高周波）の2段階効果とHIFUとの違い｜当院リピート率No.1のたるみ治療', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C5F8xXHO6SH/', 'C5F8xXHO6SH', 'clinic', 'メソナJのピンク・プレミアム2コース比較｜導入薬剤と当院5つのこだわりを徹底解説', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C5VczIMSJuf/', 'C5VczIMSJuf', 'clinic', 'マッサージピール（PRX-T33）とは｜コラーゲン生成を促進する浸透型ピーリングの成分・効果・施術頻度', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C57-8xIuo2w/', 'C57-8xIuo2w', 'clinic', 'KOライトとは｜赤・青LED光でダウンタイムを短縮・肌質改善・育毛まで対応する新メニュー', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C6S_XQqyI__/', 'C6S_XQqyI__', 'clinic', 'Maison PUREJUへの初めてのご来院前に知っておきたいQ&A｜予約・カウンセリング・持ち物', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C6sy3ykOA2W/', 'C6sy3ykOA2W', 'clinic', 'Maison PUREJUのハイフ（HIFU）｜ULTRAcel[zi:]で行うオーダーメイドたるみ治療の3つのこだわり', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C7RAVYfu-lV/', 'C7RAVYfu-lV', 'clinic', 'ポテンツァとサーマニードルの違い｜マイクロニードルRF2機種の特徴・適応・選び方を比較', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C78v2KASlP4/', 'C78v2KASlP4', 'clinic', 'あなたのたるみはどのタイプ？原因3タイプ別おすすめ治療を医師が解説', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C8EYewSOYf3/', 'C8EYewSOYf3', 'clinic', '脂性肌におすすめのスキンケア3選｜皮脂ケア3つのポイントと厳選アイテムを解説', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C8oVDlOSPjO/', 'C8oVDlOSPjO', 'clinic', 'ポテンツァとは｜ニードル×RF×薬剤導入のトリプル効果で毛穴・ニキビ跡・肝斑を改善', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C89IefLyqve/', 'C89IefLyqve', 'clinic', 'Maison PUREJUのこだわり｜空間・部屋・アメニティ・患者様との関わりに込めた想い', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C9MKol2SPFX/', 'C9MKol2SPFX', 'clinic', 'スタッフが実際に飲む美容内服3選｜ビタミンB・C・E・亜鉛・飲む日焼け止めの使い分け', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C9Rkd5Yy7GY/', 'C9Rkd5Yy7GY', 'clinic', '目周りのダウンタイムを隠す方法｜服装アイテムと内出血を消すコンシーラーの使い方', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C91v3JsSVRn/', 'C91v3JsSVRn', 'clinic', 'スタッフのスキンケア事情を大公開｜脂性肌・乾燥肌タイプ別ドクターズコスメの使い方', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C99T69kS4U4/', 'C99T69kS4U4', 'clinic', '脂肪溶解注射は効果ない？｜チンセラプラスのデオキシコール酸濃度と注入量が結果を左右する理由', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C-yyrQXSq1Z/', 'C-yyrQXSq1Z', 'clinic', 'ハイフ×高周波（サーマZI）を組み合わせるメリット｜全層に熱を加える立体たるみ治療', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C-9vWATyTmk/', 'C-9vWATyTmk', 'clinic', 'シミ治療を成功させる鍵はプレトリートメント｜内服・スキンケアで炎症後色素沈着を予防する方法', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C_NXu-ky-iB/', 'C_NXu-ky-iB', 'clinic', '夏のニキビの原因と治療法｜紫外線・エアコン乾燥・皮脂過剰・ターンオーバー乱れへの4つのアプローチ', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/C_pN031ycAj/', 'C_pN031ycAj', 'clinic', 'スタッフ推し日焼け止め3選｜吸収剤・散乱剤の違いと夏の選び方ポイント', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DADIxA-yG5l/', 'DADIxA-yG5l', 'clinic', '高濃度ビタミンC点滴とは｜内服との違い・吸収率・7つの効果と受ける前に知っておくG6PD検査', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DAniAYQyEXq/', 'DAniAYQyEXq', 'clinic', 'たるみ治療まとめ｜予防・引き締め・引き上げの3STEPと施術の選び方を医師が解説', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DBBTFajzJB-/', 'DBBTFajzJB-', 'clinic', 'ペリカンリフトとは｜あご下・二重顎のたるみを複合的に改善する手術の仕組みと適応', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DBs_rcWTlBv/', 'DBs_rcWTlBv', 'clinic', 'ビタミンCが肌に効く理由｜シミ・毛穴・ニキビ・ハリ不足への作用とQ&A', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DByX1IYzUjR/', 'DByX1IYzUjR', 'clinic', 'ボトックスでできること｜動的シワ・小顔・汗止め・リフトアップまで用途と効果をQ&Aで解説', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DCI3GaiyG_2/', 'DCI3GaiyG_2', 'clinic', 'シミの種類4つを徹底解説｜ADM・そばかす・老人性色素斑・肝斑の特徴とおすすめ治療', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DC6NrPVSmD_/', 'DC6NrPVSmD_', 'clinic', 'セレックVの9波長カスタマイズ治療｜シミ×赤み×小じわを1台で同時改善できる理由と症例', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DEE-Ti9S__W/', 'DEE-Ti9S__W', 'clinic', '乾燥肌におすすめの高保湿スキンケア3選｜保湿・バリア機能・エイジングケアを叶えるドクターズコスメ', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DFPZdhvSRWl/', 'DFPZdhvSRWl', 'clinic', 'カスタマイズレーザーとは｜ジェネシス・トーニング・フラクショナルの3種組み合わせでシミ・くすみ・毛穴を一気に改善', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DGh9GhoSgeq/', 'DGh9GhoSgeq', 'clinic', 'RF（ラジオ波）の加熱原理2種類｜ジュール熱と誘電加熱の違いと自分に合う機器の選び方', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DIn2v7_TDKf/', 'DIn2v7_TDKf', 'clinic', 'Lekarka フレグランスUVカットスプレー｜メイクの上からOK・髪・首・デコルテにも使えるマルチUVミスト', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DJoQKlzzpTi/', 'DJoQKlzzpTi', 'clinic', '糸リフト×複合治療｜ヒアルロン酸・RF・ショートスレッド・脂肪溶解を組み合わせた輪郭美の作り方', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DKmAHCeSd3L/', 'DKmAHCeSd3L', 'clinic', 'サーマジェン症例｜高周波たるみ治療の2段階効果と当院こだわりのオーダーメイド照射', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DKooQzTy40c/', 'DKooQzTy40c', 'clinic', 'ゼオスキン ロザトロール｜赤ら顔・酒さ・過剰な皮脂に着目した美容液の成分と効果', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DKttF2eyMBD/', 'DKttF2eyMBD', 'clinic', 'Maison PUREJUが静脈麻酔を使う理由｜痛みを軽減して最大効果を引き出す当院の麻酔方針', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DK_yVjqz2F7/', 'DK_yVjqz2F7', 'clinic', 'ピーリング5種類を比較｜ミラノリピール・マッサージピール・ペパーミント・メイクアップ・マヌカの選び方', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DLHkBfJzdu8/', 'DLHkBfJzdu8', 'clinic', 'スタッフのたるみ治療年間計画｜アラサー・アラフォー看護師のリアルな施術スケジュール', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DLZfMtEzCvH/', 'DLZfMtEzCvH', 'clinic', '飲む紫外線対策サプリ3選｜日焼け前・日焼け後・日常ケア別おすすめ内服と選び方', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DLo8v5_yLb2/', 'DLo8v5_yLb2', 'clinic', 'ジェネシス×ピーリング（ジェネピ）｜表皮から真皮まで働きかける夏の美肌ケアコンビ', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DLuI9ygzsOB/', 'DLuI9ygzsOB', 'clinic', '美白コスメ4選｜メラニンの仕組みとビタミンC・システアミン・トラネキサム酸・ハイドロキノンの働き', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DLymuR0y5fB/', 'DLymuR0y5fB', 'clinic', 'XERF（ザーフ）×HIFU（ハイフ）｜2種の周波数と超音波を組み合わせた全層たるみ治療の仕組みと症例', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DMHhrCoz97x/', 'DMHhrCoz97x', 'clinic', '2025年上半期 人気治療ベスト3｜XERF・うるおいシルキー注射・ジェネシスが選ばれる理由', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DMKbDoryiIw/', 'DMKbDoryiIw', 'clinic', 'Maison PUREJUの10種類の医療機器｜たるみ・シミ・毛穴など悩み別カスタマイズ治療の選び方', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DMcgsVUS1sw/', 'DMcgsVUS1sw', 'clinic', '日焼け後のレスキューケア｜メソナJ×高濃度ビタミンC点滴でUV-A・UV-Bダメージを内外からWアプローチ', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DMoreFRSHMg/', 'DMoreFRSHMg', 'clinic', 'XERF（ザーフ）症例集｜痛みが少ない最新RFたるみ治療の効果と術後の変化', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DMufZiJSjT9/', 'DMufZiJSjT9', 'clinic', '肌のベタつきを解消する3つのアプローチ｜内服・外用・施術でテカリ・ニキビ・毛穴をケア', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DNAm5CLSywl/', 'DNAm5CLSywl', 'clinic', 'ナノエッグ UV＆DTリセット ホワイトサプリメント｜リニューアルで配合量20%UPした日焼け後＆ダウンタイムケアサプリ', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DNFuqaSSInK/', 'DNFuqaSSInK', 'clinic', 'たるみ治療4層別アプローチ（機械編）｜SMAS・脂肪層・真皮深層・真皮浅層ごとに最適な機器を解説', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DNShgk7yMQq/', 'DNShgk7yMQq', 'clinic', 'ソフウェーブとは｜厚生労働省承認の超音波たるみ治療で「お顔のアイロン」効果・皮膚引き締め・小じわ改善', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DNZl73jyOA0/', 'DNZl73jyOA0', 'clinic', '皮膚たるみに特化した治療3選｜ソフウェーブ・ショートスレッド・ニードルRFで真皮層から引き締め', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DNu_PsAZpnJ/', 'DNu_PsAZpnJ', 'clinic', 'ブレッシングとは｜世界初の傾斜ニードルRFでポテンツァより広範囲・コラーゲン12倍・薬剤漏れ低減を実現', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DN-S2VAkmp6/', 'DN-S2VAkmp6', 'clinic', '顔の赤みにはセレックV｜9種類のフィルターで赤み・シミ・くすみ・毛穴をオーダーメイドで改善するIPL治療', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DOS6GAAkvuv/', 'DOS6GAAkvuv', 'clinic', '夏疲れ肌を癒すスキンケア3選｜ナビジョンDR・レカルカDREX・リビジョンDEJで肌再生とハリアップ', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DOiUWCFEhOK/', 'DOiUWCFEhOK', 'clinic', '肌治療後のダウンタイムにおすすめのスキンケア3選｜レカルカDREX・ピュレアジーで敏感肌の回復をサポート', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DPV9F87EsYn/', 'DPV9F87EsYn', 'clinic', 'Maison PUREJUの15種類の医療機器（2025年10月最新）｜たるみ治療だけで6種類、カスタマイズ治療の選び方', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DQYrl1UEjlg/', 'DQYrl1UEjlg', 'clinic', 'お手元の若返り術2選｜ヒアルロン酸・シルキー注射で手のシワ・すじ・血管をケアする方法', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DRWhTLfkpfZ/', 'DRWhTLfkpfZ', 'clinic', 'お悩み別おすすめ施術4選｜バランス・たるみ予防・皮だるみ・ツヤ肌それぞれに最適な治療とは', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DRy0lAYkt6P/', 'DRy0lAYkt6P', 'clinic', 'POLAから誕生した医療機関専売スキンケア「Dive（ダイヴ）」｜美白・シワ改善の独自成分を解説', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DSmYCEXkqf-/', 'DSmYCEXkqf-', 'clinic', 'ゼオスキン セラピューティックとは｜約3ヶ月の集中肌質改善プログラムとスタッフ実体験1ヶ月レポート', '2026-03-31', 'column', 'published'),
  ('https://www.instagram.com/p/DUc2TVYEjfB/', 'DUc2TVYEjfB', 'clinic', '肝斑治療の最新アプローチ｜トーニングだけでなくニードルRFで「肝斑ができにくい肌」を目指す', '2026-03-31', 'column', 'published')
ON CONFLICT (url) DO NOTHING;